on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push staging image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}
          repository: contoso-website
          tags: latest
  deploy:
     runs-on: ubuntu-latest
     needs: build_push_image # Will wait for the execution of the previous job
     steps:
        - uses: actions/checkout@v2
        - name: Install Helm
          uses: Azure/setup-helm@v2.0
          with:
           version: latest
        - name: Azure Kubernetes set context
          uses: Azure/aks-set-context@v1.1
          with:
            # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
            creds:  ${{ secrets.AZURE_CREDENTIALS }} 
            # Resource Group Name
            resource-group: mslearn-gh-pipelines-6500 
            # AKS Cluster Name
            cluster-name: contoso-video       
        - name: Run Helm Deploy
          run: |
            helm upgrade \
              --install \
              --create-namespace \
              --wait \
              --timeout 30m \
              --namespace staging \
              contoso-website \
              ./kubernetes/contoso-website \
              --set image.repository=${{ secrets.ACR_NAME }} \
              --set dns.name=${{ secrets.DNS_NAME }}
    
   
